### PR TITLE
Init: wish and 3 rules #28

### PR DESCRIPTION
**Pull request by byungmeo**
1. Introduce your 3 rules to other
2. Get an approval from a total of 3 people.

### CODE REVIEW

**Comment by ImKunYoung** [comment]
경상도 싸나이

**Review by solchan98 — APPROVED** [review]
1년동안 재밌게 활동해요!

**Review by ImKunYoung — APPROVED** [review]
:0

**Review by sangminee — APPROVED** [review]
잘 부탁드려요~

**Pull request merged**
